export const colors = {
  light: {
    background: "#ffffff",
    text: "#111111",
    buttonBg: "#eee",
    buttonText: "#111",
    border: "#aaa",
    selectBg: "#fff",
    selectText: "#111",
    editorBg: "#ffffff", // 👈 new
    editorBorder: "#ddd", // 👈 new
  },
  dark: {
    background: "#1e1e1e",
    text: "#f5f5f5",
    buttonBg: "#333",
    buttonText: "#f5f5f5",
    border: "#aaa",
    selectBg: "#333",
    selectText: "#f5f5f5",
    editorBg: "#1e1e1e", // 👈 new
    editorBorder: "#444", // 👈 new
  },
  console: {
    darkBg: "#0b1220",
    darkText: "#b4f8c8",
    lightBg: "#f5f5f5",
    lightText: "#111111",
  },
};

export const themes = {
  light: {
    name: "Light",
    background: "#ffffff",
    text: "#111111",
    buttonBg: "#eee",
    buttonText: "#111",
    border: "#aaa",
    selectBg: "#fff",
    selectText: "#111",
    editorBg: "#ffffff",
    editorBorder: "#ddd",
    consoleBg: "#f5f5f5",
    consoleText: "#111111",
    monaco: "light",
  },
  dark: {
    name: "Dark",
    background: "#1e1e1e",
    text: "#f5f5f5",
    buttonBg: "#333",
    buttonText: "#f5f5f5",
    border: "#aaa",
    selectBg: "#333",
    selectText: "#f5f5f5",
    editorBg: "#1e1e1e",
    editorBorder: "#444",
    consoleBg: "#0b1220",
    consoleText: "#b4f8c8",
    monaco: "vs-dark",
  },
  solarized: {
    name: "Solarized",
    background: "#fdf6e3",
    text: "#657b83",
    buttonBg: "#eee8d5",
    buttonText: "#586e75",
    border: "#93a1a1",
    selectBg: "#eee8d5",
    selectText: "#657b83",
    editorBg: "#fdf6e3",
    editorBorder: "#93a1a1",
    consoleBg: "#eee8d5",
    consoleText: "#586e75",
    monaco: "light",
  },
  neon: {
    name: "Neon",
    background: "#0f0f0f",
    text: "#39ff14",
    buttonBg: "#1a1a1a",
    buttonText: "#39ff14",
    border: "#39ff14",
    selectBg: "#1a1a1a",
    selectText: "#39ff14",
    editorBg: "#0f0f0f",
    editorBorder: "#39ff14",
    consoleBg: "#000000",
    consoleText: "#39ff14",
    monaco: "vs-dark",
  },
  dracula: {
    name: "Dracula",
    background: "#282a36",
    text: "#f8f8f2",
    buttonBg: "#44475a",
    buttonText: "#f8f8f2",
    border: "#6272a4",
    selectBg: "#44475a",
    selectText: "#f8f8f2",
    editorBg: "#282a36",
    editorBorder: "#6272a4",
    consoleBg: "#1e1f29",
    consoleText: "#f8f8f2",
    monaco: "vs-dark",
  },
};

export type ThemeKey = keyof typeof themes;
